// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyEshop_2.Data;

#nullable disable

namespace MyEshop_2.Migrations
{
    [DbContext(typeof(MyEshopContext2))]
    [Migration("20220708065945_InitialTableSeed")]
    partial class InitialTableSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MyEshop_2.Models.Category", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Description = "محصولات حوزه دیجیتال مانند گوشی و تبلت و لپتاپ",
                            name = "کالای دیجیتال"
                        },
                        new
                        {
                            id = 2,
                            Description = "لوازم جانبی ابزار کامپیوتر",
                            name = "لوازم کامپیوتر"
                        },
                        new
                        {
                            id = 3,
                            Description = " تمامی لوازم مورد نیاز شما برای عکاسی حرفه ای",
                            name = "لوازم عکاسی"
                        },
                        new
                        {
                            id = 4,
                            Description = "کلیه لوازم صوتی تصویری خانه خود را از ما بخواهید",
                            name = "صوتی تصویری"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
